# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers: 
  - Canada-Joose 
  - froggy1014 
  - LHG4650 
  - team-gigang 
  - wnsals1346

